### ISSUE TITLE
Dropbox upload error

### ISSUE THREAD

**Issue by carltonnorthern** [milesburton/teslacam#25]
I am getting this over and over again.

> docker logs 0e68aea53b3f
TeslaCam Dropbox Upload daemon
(node:1) ExperimentalWarning: The fs.promises API is experimental
(node:1) UnhandledPromiseRejectionWarning: Error: Warning, getFiles called under SSH, This will not work.
    at getFiles (/usr/local/teslacam/src/common.js:74:11)
    at init (/usr/local/teslacam/src/dropbox-upload.js:66:25)
    at Object.<anonymous> (/usr/local/teslacam/src/dropbox-upload.js:78:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by davidajacobus** [comment]
I'm seeing the same issue @carltonnorthern.

**Comment by MichaelRecht** [comment]
Same issue here

**Comment by milesburton** [comment]
I'd have to look into this, SSH was added via another developer and it was never supported by myself.
